//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by bender.rc
//
#define IDB_BITMAP_GRAP1                1
#define IDC_BUTTON_OPEN                 6
#define IDC_BUTTON_SAVEAS               7
#define IDD_BENDER_DIALOG               102
#define IDD_DIALOG_NEST                 103
#define IDD_DIALOG_NESTSIZE             104
#define IDD_DIALOG_NESTNUM              105
#define IDR_MAINFRAME                   128
#define IDD_DIALOG_NEST_SAVE            131
#define IDD_DIALOG_SAVE                 132
#define IDD_DIALOG_MOTION               133
#define IDI_GREEN_LED_ICON              135
#define IDI_GRAY_LED_ICON               136
#define IDD_DIALOG_MACHINE              144
#define IDD_GRAPH_EDITOR                146
#define IDD_DIALOG_AFXMESSAGE           147
#define IDD_DIALOG_SN                   157
#define IDD_DIALOG_GALIL                160
#define IDD_DIALOG_KEYNUMBER            162
#define IDD_DIALOG_KEYCHAR              163
#define IDD_DIALOG_PATHTWO              170
#define IDD_DIALOG_GLASS                171
#define IDD_DIALOG_HAND                 174
#define IDD_DIALOG_AFFIRM               176
#define IDD_SYS_PASS                    181
#define IDD_DIALOG_USELIMIT             182
#define IDD_SYS_SUPER                   185
#define IDD_DIALOG_FILEMANAGER          186
#define IDD_DIALOG_CONFIG_LIGHT         187
#define IDD_DIALOG_RUN                  201
#define IDC_COMBO_CEX                   212
#define IDC_COMBO_CEY                   213
#define IDC_COMBO_CEZ                   214
#define IDC_COMBO_CEW                   215
#define IDC_COMBO_CE2X                  216
#define IDD_DIALOG_CONFIG_SCAN          216
#define IDC_COMBO_CE2Y                  217
#define IDC_COMBO_CE2Z                  218
#define IDC_COMBO_CE2W                  219
#define IDD_DIALOG_BOTTERO              219
#define IDC_COMBO_CEE                   220
#define IDC_COMBO_CE2E                  221
#define IDD_DIALOG_CUTTINGSIZE          225
#define IDC_COMBO_OEX                   228
#define IDI_ICON_COMOK                  228
#define IDC_COMBO_OEY                   229
#define IDC_COMBO_OEZ                   230
#define IDC_COMBO_OEW                   231
#define IDC_COMBO_MOX                   232
#define IDC_COMBO_MOY                   233
#define IDC_COMBO_MOZ                   234
#define IDC_COMBO_MOW                   235
#define IDD_DIALOG_CONFIG               235
#define IDC_COMBO_OEE                   236
#define IDC_COMBO_MOE                   237
#define IDD_DIALOG_CONFIG_LOADING       238
#define IDI_ICON_GRAPH                  238
#define IDI_ICON_LINE                   243
#define IDI_ICON_G2                     244
#define IDI_ICON_G3                     248
#define IDC_COMBO_MTX                   256
#define IDC_COMBO_MTY                   257
#define IDC_COMBO_MTZ                   258
#define IDC_COMBO_MTW                   259
#define IDC_COMBO_MTE                   260
#define IDB_IMAGES                      270
#define IDC_EDIT_KDX                    273
#define IDC_EDIT_KDY                    274
#define IDC_EDIT_KDZ                    275
#define IDC_EDIT_KDW                    276
#define IDC_EDIT_KPX                    277
#define IDC_EDIT_KPY                    278
#define IDC_EDIT_KPZ                    279
#define IDC_EDIT_KPW                    280
#define IDC_EDIT_KIX                    281
#define IDC_EDIT_KIY                    282
#define IDC_EDIT_KIZ                    283
#define IDC_EDIT_KIW                    284
#define IDC_EDIT_KDE                    285
#define IDC_EDIT_KPE                    286
#define IDC_EDIT_KIE                    287
#define IDD_DIALOG_CONFIG_OILING        293
#define IDD_DIALOG_MACHINE_CASE         294
#define IDD_DIALOG_DRAW_CAD             295
#define IDC_EDIT_KSX                    307
#define IDC_EDIT_KSY                    308
#define IDC_EDIT_KSZ                    309
#define IDC_EDIT_KSW                    310
#define IDC_EDIT_KSE                    312
#define IDC_STATIC_TITLE                317
#define IDD_DIALOG_SHOWEXTRA            323
#define IDB_BITMAP1                     324
#define IDD_DIALOG_TEST                 328
#define IDD_DIALOG_BACKUP               329
#define IDB_BITMAP_FILETYPE             331
#define IDB_BITMAP_HAND1                333
#define IDB_BITMAP_HAND2                334
#define IDB_BITMAP_HOME1                335
#define IDB_BITMAP_HOME2                336
#define IDB_BITMAP_AUTO2                341
#define IDB_BITMAP_AUTO1                342
#define IDB_BITMAP_SETTING2             343
#define IDB_BITMAP_SETTING1             344
#define IDB_BITMAP_GRAP2                345
#define IDB_BITMAP_EDIT2                347
#define IDB_BITMAP_EDIT1                348
#define IDB_BITMAP_DRAW2                349
#define IDB_BITMAP_DRAW1                350
#define IDB_BITMAP_LIGHTPOS2            351
#define IDB_BITMAP_LIGHTPOS1            352
#define IDB_BITMAP_CLOSE2               353
#define IDB_BITMAP_CLOSE1               354
#define IDB_BITMAP_RIGHT2               355
#define IDB_BITMAP_LEFT1                356
#define IDB_BITMAP_LEFT2                357
#define IDB_BITMAP_ZOOMOUT1             358
#define IDB_BITMAP_ZOOMOUT2             359
#define IDB_BITMAP_UP1                  360
#define IDB_BITMAP_UP2                  361
#define IDB_BITMAP_ZOOMIN1              364
#define IDB_BITMAP_ZOOMIN2              365
#define IDB_BITMAP_DOWN1                366
#define IDB_BITMAP_DOWN2                367
#define IDB_BITMAP_RIGHT1               368
#define IDB_BITMAP_ZOOM2                371
#define IDB_BITMAP_ZOOM1                372
#define IDB_BITMAP2                     373
#define IDB_BITMAP_STOP2                381
#define IDB_BITMAP_STOP1                382
#define IDB_BITMAP_STRAT2               383
#define IDB_BITMAP_OIL1                 384
#define IDB_BITMAP_OIL2                 385
#define IDB_BITMAP_STRAT1               386
#define IDB_BITMAP_BACK2                387
#define IDB_BITMAP_BACK1                388
#define IDB_BITMAP_SETPRE2              391
#define IDB_BITMAP_SETPRE1              392
#define IDB_BITMAP_SAVE2                393
#define IDB_BITMAP_SAVE1                394
#define IDB_BITMAP_ALARM1               397
#define IDB_BITMAP_ALARM2               398
#define IDB_BITMAP_HISTORY1             399
#define IDB_BITMAP_HISTORY2             400
#define IDB_BITMAP_OUT1                 401
#define IDB_BITMAP_OUT2                 402
#define IDB_BITMAP_INPUT1               403
#define IDB_BITMAP_INPUT2               404
#define IDB_BITMAP_MACH2                405
#define IDB_BITMAP_MACH1                406
#define IDB_BITMAP_EDITSET2             411
#define IDB_BITMAP_DELETE1              412
#define IDB_BITMAP_DELETE2              413
#define IDB_BITMAP_EDITSET1             414
#define IDB_BITMAP_SAVEPAR2             415
#define IDB_BITMAP_CADWAY1              416
#define IDB_BITMAP_CADWAY2              417
#define IDB_BITMAP_EDITWAY1             418
#define IDB_BITMAP_EDITWAY2             419
#define IDB_BITMAP_SAVEPAR1             420
#define IDB_BITMAP_FILE2                427
#define IDB_BITMAP_FILE1                428
#define IDB_BITMAP_PARABU2              433
#define IDB_BITMAP_PARABU1              434
#define IDB_BITMAP_SYSTEM2              441
#define IDB_BITMAP_ZEOR1                442
#define IDB_BITMAP_ZEOR2                443
#define IDB_BITMAP_SYSTEM1              444
#define IDB_BITMAP_NEST2                445
#define IDB_BITMAP_PARA1                446
#define IDB_BITMAP_PARA2                447
#define IDB_BITMAP_NEST1                448
#define IDB_BITMAP_NEW2                 449
#define IDB_BITMAP_NEW1                 450
#define IDB_BITMAP_OPEN2                451
#define IDB_BITMAP_OPEN1                452
#define IDB_BITMAP_ARC2                 453
#define IDB_BITMAP_ARC1                 454
#define IDB_BITMAP_SAVEG2               465
#define IDB_BITMAP_SAVECXF1             466
#define IDB_BITMAP_SAVECXF2             467
#define IDB_BITMAP_SAVEG1               468
#define IDB_BITMAP_SCREW2               469
#define IDB_BITMAP_CLU1                 472
#define IDB_BITMAP_CLU2                 473
#define IDB_BITMAP_CONTROL1             474
#define IDB_BITMAP_CONTROL2             475
#define IDB_BITMAP_SCREW1               476
#define IDB_BITMAP_JINGLING             481
#define IDB_BITMAP_BK                   482
#define IDB_BITMAP_BLACK                483
#define IDB_BITMAP_FIRST2               488
#define IDB_BITMAP_PRE1                 489
#define IDB_BITMAP_PRE2                 490
#define IDB_BITMAP_NEXT1                491
#define IDB_BITMAP_NEXT2                492
#define IDB_BITMAP_LAST1                493
#define IDB_BITMAP_LAST2                494
#define IDB_BITMAP_FIRST1               495
#define IDB_BITMAP_NULL2                496
#define IDB_BITMAP_NULL1                497
#define IDB_BITMAP_SPUP2                498
#define IDB_BITMAP_SPDW2                499
#define IDB_BITMAP_SPDW1                500
#define IDB_BITMAP_SPUP1                501
#define IDB_BITMAP_FORWARD2             502
#define IDB_BITMAP_REVERSE1             504
#define IDB_BITMAP_REVERSE2             505
#define IDB_BITMAP_SP11                 506
#define IDB_BITMAP_SP12                 507
#define IDB_BITMAP_SP21                 508
#define IDB_BITMAP_SP22                 509
#define IDB_BITMAP_FORWARD1             510
#define IDB_BITMAP_UD2                  511
#define IDB_BITMAP_UD1                  512
#define IDB_BITMAP_CUD2                 513
#define IDB_BITMAP_CUD1                 516
#define IDB_BITMAP_FANST1               519
#define IDB_BITMAP_FANST2               520
#define IDB_BITMAP_POS2                 521
#define IDB_BITMAP_POS1                 524
#define IDB_BITMAP_RESET2               527
#define IDB_BITMAP_RESET1               528
#define IDB_BITMAP_DIALOG               529
#define IDB_BITMAP_PPOS2                530
#define IDB_BITMAP_PPOS1                531
#define IDB_BITMAP_CSAVE2               532
#define IDB_BITMAP_CSAVE1               533
#define IDB_BITMAP_FILESTY2             534
#define IDB_BITMAP_FILESTY1             535
#define IDB_BITMAP_FILEMAN1             536
#define IDB_BITMAP_FILEMAN2             538
#define IDB_BITMAP_WCUT1                539
#define IDB_BITMAP_WCUT2                540
#define IDB_BITMAP_DLGHAND2             542
#define IDB_BITMAP_DLGHAND1             543
#define IDB_BITMAP_ADD2                 544
#define IDB_BITMAP_REMATE1              545
#define IDB_BITMAP_REMATE2              546
#define IDB_BITMAP_MOVE1                547
#define IDB_BITMAP_MOVE2                548
#define IDB_BITMAP_ADD1                 549
#define IDB_BITMAP_DELGRAP2             550
#define IDB_BITMAP_DELGRAP1             551
#define IDD_DIALOG_HOME                 553
#define IDB_BITMAP_AUTO3                554
#define IDB_BITMAP_MHOME3               555
#define IDB_BITMAP_MHOME1               556
#define IDB_BITMAP_MHOME2               557
#define IDB_BITMAP_PHOME3               558
#define IDB_BITMAP_PHOME1               559
#define IDB_BITMAP_PHOME2               560
#define IDB_BITMAP_HOMEX2               561
#define IDB_BITMAP_HOMEX1               562
#define IDB_BITMAP_SETPOS2              563
#define IDB_BITMAP_SETPOS1              564
#define IDB_BITMAP_SPORT2               565
#define IDB_BITMAP_SPORT1               566
#define IDB_BITMAP_HAND3                567
#define IDB_BITMAP_HOME3                568
#define IDB_BITMAP_NULL3                569
#define IDD_DIALOG_SHEETGLASS           570
#define IDB_BITMAP_SHEET1               573
#define IDB_BITMAP_SHEET2               574
#define IDB_BITMAP_QUREY2               575
#define IDB_BITMAP_QUREY1               576
#define IDD_DIALOG_ADJUSTDOUBLE         577
#define IDB_BITMAP_OILH2                578
#define IDB_BITMAP_OILH1                579
#define IDB_BITMAP_FORWARD3             580
#define IDB_BITMAP_REVERSE3             581
#define IDB_BITMAP_SP13                 582
#define IDB_BITMAP_SP23                 583
#define IDB_BITMAP_UD3                  584
#define IDB_BITMAP_CUD3                 585
#define IDB_BITMAP_FANST3               586
#define IDB_BITMAP_POS3                 587
#define IDB_BITMAP_OILH3                588
#define IDD_DIALOG_XY                   589
#define IDB_BITMAP_PRINT2               590
#define IDB_BITMAP_PPRE1                591
#define IDB_BITMAP_PPRE2                592
#define IDB_BITMAP_PNEXT1               593
#define IDB_BITMAP_PNEXT2               594
#define IDB_BITMAP_PRINT1               595
#define IDB_BITMAP_POPTIMA2             596
#define IDB_BITMAP_POPTIMA1             597
#define IDC_BUTTON1                     1000
#define IDC_EDIT1                       1000
#define IDC_BUTTON2                     1001
#define IDC_EDIT2                       1001
#define IDC_BUTTON3                     1002
#define IDC_EDIT3                       1002
#define IDC_EDIT4                       1003
#define IDC_BUTTON_F3                   1003
#define IDC_BUTTON_PICKUP               1003
#define IDC_BUTTON14                    1003
#define IDC_BUTTON4                     1004
#define IDC_EDIT5                       1004
#define IDC_BUTTON_SORT                 1004
#define IDC_EDIT6                       1005
#define IDC_BUTTONL1                    1005
#define IDC_BUTTON_L                    1005
#define IDC_BUTTON5                     1006
#define IDC_BUTTONS3                    1006
#define IDC_BUTTONL2                    1006
#define IDC_BUTTON_R                    1006
#define IDC_EDIT7                       1006
#define IDC_BUTTON6                     1007
#define IDC_BUTTONS4                    1007
#define IDC_BUTTONL3                    1007
#define IDC_EDIT8                       1007
#define IDC_BUTTON7                     1008
#define IDC_BUTTONS5                    1008
#define IDC_BUTTONL4                    1008
#define IDC_EDIT_SCANA                  1008
#define IDC_EDIT9                       1008
#define IDC_EDIT_SCANB                  1009
#define IDC_BUTTON8                     1009
#define IDC_EDIT10                      1009
#define IDC_EDIT_SCANC                  1010
#define IDC_BUTTON9                     1010
#define IDC_EDIT_X                      1010
#define IDC_EDIT_DAY1                   1010
#define IDC_EDIT11                      1010
#define IDC_EDIT_SCAND                  1011
#define IDC_BUTTON10                    1011
#define IDC_EDIT_YEAR2                  1011
#define IDC_EDIT12                      1011
#define IDC_EDIT_SCANE                  1012
#define IDC_EDIT_SCANF                  1013
#define IDC_BUTTON18                    1013
#define IDC_EDIT_SCANG                  1014
#define IDC_BUTTON19                    1014
#define IDC_BUTTONF7                    1015
#define IDC_BUTTONF8                    1016
#define IDC_BUTTONL9                    1019
#define IDC_EDIT_ELipseSpeed            1019
#define IDC_BUTTONL10                   1020
#define IDC_EDIT_VT                     1020
#define IDC_BUTTON_SAVE                 1022
#define IDC_BUTTON_NEW                  1023
#define IDC_STATIC_ClipX1               1028
#define IDC_BUTTON_STOP                 1029
#define IDC_STATIC_ClipY1               1029
#define IDC_BUTTON_A                    1030
#define IDC_STATIC_ClipX2               1030
#define IDC_BUTTON_B                    1031
#define IDC_STATIC_ClipY2               1031
#define IDC_EDIT_ClipX1                 1032
#define IDC_EDIT_ClipX2                 1033
#define IDC_EDIT_ClipY1                 1034
#define IDC_EDIT_ClipY2                 1035
#define IDC_STATIC_PARA01               1036
#define IDC_EDIT_PARA01                 1037
#define IDC_STATIC_PARA02               1038
#define IDC_EDIT_PARA02                 1039
#define IDC_STATIC_PARA03               1040
#define IDC_BUTTON_RUN                  1041
#define IDC_EDIT_PARA03                 1041
#define IDC_BUTTON_PAUSE                1042
#define IDC_STATIC_PARA04               1042
#define IDC_EDIT_PARA04                 1043
#define IDC_STATIC_PARA05               1044
#define IDC_EDIT_PARA05                 1045
#define IDC_STATIC_PARA06               1046
#define IDC_EDIT_PARA06                 1047
#define IDC_STATIC_PARA07               1048
#define IDC_EDIT_PARA07                 1049
#define IDC_STATIC_PARA08               1050
#define IDC_EDIT_PARA08                 1051
#define IDC_STATIC_PARA09               1052
#define IDC_EDIT_PARA09                 1053
#define IDC_STATIC_PARA10               1054
#define IDC_EDIT_PARA10                 1055
#define IDC_FEEDMOVE                    1056
#define IDC_STATIC_REMARK1              1056
#define IDC_RAPIDMOVE                   1057
#define IDC_STATIC_REMARK2              1057
#define IDC_FEEDVACC                    1058
#define IDC_STATIC_REMARK3              1058
#define IDC_FEEDVDEC                    1059
#define IDC_STATIC_REMARK4              1059
#define IDC_FEEDMOVE2                   1060
#define IDC_STATIC_REMARK5              1060
#define IDC_FEEDVACC2                   1061
#define IDC_STATIC_REMARK6              1061
#define IDC_HANDSPEEDX                  1062
#define IDC_FEEDVDEC2                   1062
#define IDC_STATIC_REMARK7              1062
#define IDC_HANDSPEEDY                  1063
#define IDC_STATIC_REMARK8              1063
#define IDC_HANDSPEEDZ                  1064
#define IDC_FEEDMOVE4                   1064
#define IDC_STATIC_REMARK9              1064
#define IDC_FEEDMOVE5                   1065
#define IDC_STATIC_REMARK10             1065
#define IDC_EDIT_PARA11                 1067
#define IDC_STATIC_REMARK11             1068
#define IDC_EDIT_PARA12                 1070
#define IDC_HANDSPEEDW                  1071
#define IDC_EDIT_MINCORNERSP            1071
#define IDC_STATIC_REMARK12             1071
#define IDC_EDIT_PARA13                 1073
#define IDC_STATIC_REMARK13             1074
#define IDC_EDIT_PARA14                 1076
#define IDC_STATIC_REMARK14             1077
#define IDC_EDIT_PARA15                 1079
#define IDC_STATIC_REMARK15             1080
#define IDC_EDIT_PASS                   1083
#define IDC_BUTTONS1                    1089
#define IDC_BUTTONL6                    1089
#define IDC_BUTTONS9                    1090
#define IDC_EDIT_PUSLX                  1095
#define IDC_EDIT_PUSLY                  1096
#define IDC_EDIT_PUSLZ                  1097
#define IDC_EDIT_PUSLW                  1098
#define IDC_EDIT_MAXCORNER              1100
#define IDC_EDIT_BKX                    1103
#define IDC_CENTERY                     1103
#define IDC_EDIT_BKY                    1104
#define IDC_EDIT_MINCORNER              1104
#define IDC_EDIT_BKZ                    1105
#define IDC_EDIT_MINARCSP               1105
#define IDC_EDIT_BKW                    1106
#define IDC_EDIT_TANGENT                1106
#define IDC_LISTDISK                    1107
#define IDC_EDIT_MACHINEX               1111
#define IDC_EDIT_MACHINEY               1112
#define IDC_EDIT_MACHINEZ               1113
#define IDC_EDIT_MACHINEW               1114
#define IDC_EDIT_LIGHTX                 1115
#define IDC_EDIT_MACHLABELX             1115
#define IDC_EDIT_LIGHTY                 1116
#define IDC_EDIT_MACHLABELY             1116
#define IDC_EDIT_SPEEDY                 1117
#define IDC_STATIC_AFX                  1118
#define IDC_EDIT_ACCY                   1118
#define IDC_BUTTON_EXIT                 1119
#define IDC_EDIT_DECY                   1119
#define IDC_EDIT_Y                      1120
#define IDC_BUTTON_FILEMAN              1120
#define IDC_EDIT_STARTY                 1121
#define IDC_EDIT_SPEEDX                 1122
#define IDC_EDIT_ACCX                   1123
#define IDC_EDIT_DECX                   1124
#define IDC_JOURNEYPB                   1125
#define IDC_JOURNEYRB                   1126
#define IDC_JOURNEYPC                   1127
#define IDC_JOURNEYRC                   1128
#define IDC_JOURNEYPD                   1129
#define IDC_JOURNEYRD                   1130
#define IDC_ZEROOFFSETY                 1131
#define IDC_BUTTON_3DPGUP               1132
#define IDC_ZEROOFFSETZ                 1132
#define IDC_BUTTON_3DPGDN               1133
#define IDC_ZEROOFFSETW                 1133
#define IDC_BUTTON_3DUP                 1134
#define IDC_BUTTON_3DDOWN               1135
#define IDC_BUTTON_3DLEFT               1136
#define IDC_BUTTON_3DRIGHT              1137
#define IDC_BUTTON_1                    1137
#define IDC_BUTTON_2                    1138
#define IDC_LEDCTRL1                    1139
#define IDC_EDIT_OLD                    1145
#define IDC_EDIT_NEW                    1146
#define IDC_STATIC_NEW                  1147
#define IDC_STATIC_OLD                  1148
#define IDC_BUTTON_BK                   1149
#define IDC_BUTTON_DEL                  1150
#define IDC_BUTTON_DEFAULT              1150
#define IDC_OK                          1151
#define IDC_BUTTON_NEXT                 1156
#define IDC_BUTTON_PRE                  1157
#define IDC_BUTTON_LAST                 1158
#define IDC_BUTTON_FIRST                1159
#define IDC_STATICA                     1182
#define IDC_STATICB                     1183
#define IDC_STATICC                     1184
#define IDC_STATICD                     1187
#define IDC_STATICG                     1188
#define IDC_STATICD2                    1189
#define IDC_STATICD_LABEDST             1190
#define IDC_BUTTONS2                    1222
#define IDC_BUTTONL7                    1222
#define IDC_BUTTONS10                   1223
#define IDC_BUTTON_3                    1224
#define IDC_BUTTON_4                    1225
#define IDC_BUTTON_5                    1226
#define IDC_STATIC_T                    1227
#define IDC_BUTTON_6                    1227
#define IDC_STATICE                     1228
#define IDC_BUTTON_7                    1228
#define IDC_STATICF                     1229
#define IDC_BUTTONL8                    1229
#define IDC_BUTTON_8                    1229
#define IDC_BUTTON_9                    1230
#define IDC_BUTTONS7                    1231
#define IDC_BUTTON_0                    1231
#define IDC_BUTTONS8                    1232
#define IDC_BUTTON_BACKSPACE            1232
#define IDC_BUTTON_Q                    1233
#define IDC_BUTTON_E                    1235
#define IDC_BUTTON_SPDN                 1236
#define IDC_BUTTON_SPUP                 1237
#define IDC_BUTTON_T                    1237
#define IDC_BUTTON_AODN                 1238
#define IDC_BUTTON_U                    1239
#define IDC_BUTTON_AOUP                 1239
#define IDC_BUTTON_I                    1240
#define IDC_BUTTON_O                    1241
#define IDC_BUTTON_P                    1242
#define IDC_BUTTON_DIRECTORY            1243
#define IDC_BUTTON_S                    1245
#define IDC_BUTTON_D                    1246
#define IDC_BUTTON_F                    1247
#define IDC_CENTERX                     1249
#define IDC_BUTTON_H                    1249
#define IDC_BUTTON_C3                   1249
#define IDC_EDIT_MINRADIUS              1250
#define IDC_BUTTON_J                    1250
#define IDC_BUTTON_A3                   1250
#define IDC_BUTTON_K                    1251
#define IDC_BUTTON_D3                   1251
#define IDC_EDIT_MAXRADIUS              1251
#define IDC_BUTTON_QUOTATIONMARK        1252
#define IDC_BUTTON_ENTER                1253
#define IDC_BUTTON_SHIFTL               1254
#define IDC_EDIT_X1                     1256
#define IDC_EDIT_X2                     1257
#define IDC_BUTTON_C                    1257
#define IDC_EDIT_Y1                     1258
#define IDC_BUTTON_V                    1258
#define IDC_EDIT_Y2                     1259
#define IDC_EDIT_STARTX                 1260
#define IDC_BUTTON_N                    1260
#define IDC_BUTTON_M                    1261
#define IDC_STATIC_INFO                 1262
#define IDC_BUTTON_COMMA                1262
#define IDC_BUTTON_SHIFTR               1263
#define IDC_BUTTON_SUB                  1264
#define IDC_BUTTON_EQUATION             1265
#define IDC_BUTTON_INCLUDEL             1266
#define IDC_BUTTON_INCLUDER             1267
#define IDC_EDIT_2                      1268
#define IDC_BUTTON_SEMICOLON            1269
#define IDC_BUTTON_POINT                1270
#define IDC_BUTTON_DIVIDE               1271
#define IDC_STATIC_LENGH                1276
#define IDC_BUTTON_LEFT                 1281
#define IDC_BUTTON_RIGHT                1282
#define IDC_BUTTON_G                    1290
#define IDC_DEMO10CTRL1                 1301
#define IDC_DEMO10CTRL2                 1302
#define IDC_BUTTON11                    1303
#define IDC_BUTTON12                    1304
#define IDC_BUTTON13                    1305
#define IDC_BUTTON_X                    1308
#define IDC_BUTTON_HOME                 1308
#define IDC_BUTTON_Y                    1309
#define IDC_BUTTON_SPSUB                1309
#define IDC_BUTTON_Z                    1310
#define IDC_BUTTON_SPADD                1310
#define IDC_BUTTON_END                  1311
#define IDC_EDIT_BEGINX                 1312
#define IDC_EDIT_BEGINY                 1313
#define IDC_EDITX                       1317
#define IDC_EDITY                       1318
#define IDC_BUTTON_RETURN               1318
#define IDC_EDITZ                       1319
#define IDC_STATICX                     1320
#define IDC_STATICY                     1321
#define IDC_STATICMAX                   1321
#define IDC_STATICZ                     1322
#define IDC_STATICREMAIN                1322
#define IDC_STATICXMAX                  1323
#define IDC_STATICXREMAIN               1324
#define IDC_BUTTON_UP                   1325
#define IDC_BUTTON_DOWN                 1326
#define IDC_STATICW                     1327
#define IDC_STATICWMAX                  1328
#define IDC_STATICWREMAIN               1329
#define IDC_BUTTON_W                    1331
#define IDC_BUTTON_UP1                  1334
#define IDC_BUTTON_DOWN1                1335
#define IDC_BUTTON_LEFT1                1336
#define IDC_BUTTON_RIGHT1               1337
#define IDC_BUTTON_SOFTPASS1            1349
#define IDC_BUTTON_SOFTPASS2            1350
#define IDC_MONTHCALENDAR1              1354
#define IDC_STATIC_1                    1358
#define IDC_STATIC_DAY                  1358
#define IDC_STATIC_2                    1359
#define IDC_EDIT_YEAR1                  1359
#define IDC_STATIC_3                    1360
#define IDC_EDIT_MONTH1                 1360
#define IDC_LISTREMOVE                  1361
#define IDC_DISPLAY_MAININF             1367
#define IDC_STATICH                     1373
#define IDC_BUTTON_A0                   1390
#define IDC_BUTTON_B0                   1391
#define IDC_BUTTON_C0                   1392
#define IDC_BUTTON_D0                   1393
#define IDC_STATIC16                    1394
#define IDC_BUTTON_E0                   1394
#define IDC_BUTTON_F0                   1395
#define IDC_STATIC30                    1396
#define IDC_BUTTON_G0                   1396
#define IDC_BUTTON_A1                   1397
#define IDC_STATIC_ELipse               1397
#define IDC_BUTTON_B1                   1398
#define IDC_STATIC_VT                   1398
#define IDC_BUTTON_C1                   1399
#define IDC_LIST1                       1400
#define IDC_BUTTON_D1                   1400
#define IDC_BUTTON_F1                   1402
#define IDC_BUTTON_A2                   1404
#define IDC_BUTTON_B2                   1405
#define IDC_BUTTON_D2                   1407
#define IDC_BUTTON_F2                   1409
#define IDC_STATIC_FILE                 1410
#define IDC_BUTTON_H0                   1412
#define IDC_BUTTON_DP                   1413
#define IDC_STATICt0                    1427
#define IDC_STATICt1                    1428
#define IDC_STATICt2                    1429
#define IDC_STATICt3                    1430
#define IDC_RADIO1                      1430
#define IDC_STATICt4                    1431
#define IDC_RADIO2                      1431
#define IDC_STATICt5                    1432
#define IDC_RADIO3                      1432
#define IDC_RADIO_LANGUAGE3             1432
#define IDC_STATICt6                    1433
#define IDC_RADIO9                      1433
#define IDC_STATICt7                    1434
#define IDC_LIST_BOTTERO                1434
#define IDC_RADIO10                     1434
#define IDC_STATICt8                    1435
#define IDC_BUTTON_F4                   1435
#define IDC_RADIO11                     1435
#define IDC_BUTTON_F5                   1436
#define IDC_RADIO12                     1436
#define IDC_STATICt10                   1437
#define IDC_BUTTON_F6                   1437
#define IDC_BUTTON_F7                   1438
#define IDC_STATICt12                   1439
#define IDC_BUTTON_F8                   1439
#define IDC_STATICt13                   1440
#define IDC_BUTTON_UPDATE               1440
#define IDC_STATICt14                   1441
#define IDC_STATICt15                   1442
#define IDC_EDIT_VALUE                  1442
#define IDC_STATICt16                   1443
#define IDC_STATIC1                     1445
#define IDC_STATIC2                     1446
#define IDC_BUTTON_SETUP                1446
#define IDC_STATIC3                     1447
#define IDC_STATIC4                     1448
#define IDC_STATIC5                     1449
#define IDC_STATIC6                     1450
#define IDC_STATIC7                     1451
#define IDC_STATIC8                     1452
#define IDC_STATIC9                     1453
#define IDC_BUTTON_PREV1                1453
#define IDC_STATIC10                    1454
#define IDC_STATIC_SIZEA                1454
#define IDC_STATIC11                    1455
#define IDC_STATIC_SIZEB                1455
#define IDC_STATIC12                    1456
#define IDC_STATIC_SIZEC                1456
#define IDC_STATIC26                    1457
#define IDC_STATIC_SIZED                1457
#define IDC_STATIC27                    1458
#define IDC_STATIC_SIZEE                1458
#define IDC_STATIC28                    1459
#define IDC_STATIC_DXFA                 1459
#define IDC_STATIC32                    1460
#define IDC_STATIC_DXFB                 1460
#define IDC_STATIC33                    1461
#define IDC_STATIC_DXFC                 1461
#define IDC_STATIC34                    1462
#define IDC_STATIC_DXFD                 1462
#define IDC_STATIC37                    1463
#define IDC_STATIC_SCANA                1463
#define IDC_STATIC_SAFEDOWN             1463
#define IDC_STATIC38                    1464
#define IDC_STATIC_SCANB                1464
#define IDC_STATIC_SCANC                1465
#define IDC_STATIC_MAC8                 1465
#define IDC_STATIC_MAXRADIU             1465
#define IDC_STATIC_SCAND                1466
#define IDC_STATIC_SCANE                1467
#define IDC_STATIC_SCANF                1468
#define IDC_STATIC_SCANG                1469
#define IDC_STATIC_SIZE                 1475
#define IDC_STATIC_TECHNICS             1485
#define IDC_CHECK_TECH4                 1486
#define IDC_CHECK_TECH5                 1487
#define IDC_CHECK_TECH7                 1489
#define IDC_CHECK_TECH1                 1491
#define IDC_STATIC_LANGUAGE             1493
#define IDC_RADIO_LANGUAGE1             1494
#define IDC_RADIO_LANGUAGE2             1495
#define IDC_STATIC_PHOTOTUBE            1496
#define IDC_RADIO_PHOTOTUBE1            1497
#define IDC_RADIO_PHOTOTUBE2            1498
#define IDC_RADIO_PHOTOTUBE3            1499
#define IDC_RADIO_PHOTOTUBE4            1500
#define IDC_STATIC_DXF                  1501
#define IDC_RADIO_DXF1                  1502
#define IDC_RADIO_DXF2                  1503
#define IDC_RADIO_DXF3                  1504
#define IDC_RADIO_SORTSHORT             1505
#define IDC_RADIO_LOAD1                 1506
#define IDC_RADIO_LOAD2                 1507
#define IDC_STATIC_LOAD                 1508
#define IDC_RADIO_UNIT1                 1509
#define IDC_EDIT_SIZEA                  1510
#define IDC_RADIO_UNIT2                 1510
#define IDC_EDIT_SIZEB                  1511
#define IDC_STATIC_UNIT                 1511
#define IDC_EDIT_SIZEC                  1512
#define IDC_ZEROSPEEDX                  1512
#define IDC_STATIC_SORT                 1512
#define IDC_EDIT_SIZED                  1513
#define IDC_ZEROSPEEDY                  1513
#define IDC_RADIO_CONTROLA              1513
#define IDC_EDIT_SIZEE                  1514
#define IDC_ZEROSPEEDZ                  1514
#define IDC_STATIC_CONTROL              1514
#define IDC_ZEROSPEEDW                  1515
#define IDC_EDIT_SAFEDOWN               1515
#define IDC_RADIO_SHELF1                1515
#define IDC_COMBO_ZEROX                 1516
#define IDC_STATIC_SHELF                1516
#define IDC_COMBO_ZEROY                 1517
#define IDC_STATIC_SAFE                 1517
#define IDC_COMBO_ZEROZ                 1518
#define IDC_COMBO_ZEROW                 1519
#define IDC_EDIT_DXFA                   1520
#define IDC_ZEROOFFSETX                 1520
#define IDC_EDIT_DXFB                   1521
#define IDC_JOURNEYRA                   1521
#define IDC_LIST_ALARM                  1521
#define IDC_EDIT_DXFC                   1522
#define IDC_JOURNEYPA                   1522
#define IDC_EDIT_DXFD                   1523
#define IDC_ACCX                        1523
#define IDC_ACCY                        1524
#define IDC_ACCZ                        1525
#define IDC_ACCW                        1526
#define IDC_DECX                        1527
#define IDC_CHECK_TECH9                 1527
#define IDC_DECY                        1528
#define IDC_DECZ                        1529
#define IDC_DECW                        1530
#define IDC_STATIC_MAC4                 1535
#define IDC_STATIC_MAC6                 1536
#define IDC_STATIC_MAC7                 1537
#define IDC_STATIC_MAC9                 1538
#define IDC_STATIC_MAC10                1539
#define IDC_STATIC_MAC11                1540
#define IDC_STATIC_MAC12                1541
#define IDC_STATIC_MAC13                1542
#define IDC_STATIC_MAC14                1543
#define IDC_STATIC_MAC15                1544
#define IDC_STATIC_MAC16                1545
#define IDC_EDIT_WAITX                  1546
#define IDC_STATIC_MAC17                1546
#define IDC_EDIT_WAITY                  1547
#define IDC_EDIT_DelayTime              1548
#define IDC_EDIT_DelayTime2             1549
#define IDC_EDIT_LABELWT                1550
#define IDC_BUTTON_I0                   1552
#define IDC_BUTTON_INVERSEX             1553
#define IDC_BUTTON_DIRECTX              1554
#define IDC_BUTTON_INVERSEY             1555
#define IDC_BUTTON_DIRECTY              1556
#define IDC_BUTTON_PACE                 1557
#define IDC_BUTTON_DIRECTZ              1558
#define IDC_BUTTON_INVERSEZ             1559
#define IDC_STATIC_CURRPOS              1559
#define IDC_CHECK_MACH1                 1560
#define IDC_TREECTL                     1560
#define IDC_RADIO_SORTPOINT             1561
#define IDC_SCROLLBAR_Y                 1561
#define IDC_STATIC_COMMAND              1562
#define IDC_CHECK_MACH2                 1562
#define IDC_SCROLLBAR_X                 1562
#define IDC_RADIO_CONTROLB              1563
#define IDC_STATIC_SCAN                 1563
#define IDC_STATIC_MACHINE              1564
#define IDC_RADIO_SHELF2                1564
#define IDC_STATIC_GLASS                1565
#define IDC_STATIC_SCAN_PACE            1565
#define IDC_CHECK_PRINT                 1565
#define IDC_STATIC_BORDER               1566
#define IDC_STATIC_SCAN_BEGINX          1566
#define IDC_CHECK_POSNEG                1566
#define IDC_STATIC_SCAN_BEGINY          1567
#define IDC_RADIO_CONTROLC              1567
#define IDC_EDIT_OILOPEN                1568
#define IDC_STATIC_SCAN_CENTERX         1568
#define IDC_EDIT_OILCLOSE               1569
#define IDC_EDIT_PACE                   1569
#define IDC_PRESSURE                    1570
#define IDC_EDIT_CENTERX                1570
#define IDC_BUTTON_PREV                 1571
#define IDC_STATIC_BEGIN                1571
#define IDC_STATIC_SCAN_CENTERY         1571
#define IDC_BUTTON_F9                   1572
#define IDC_STATIC_MID                  1572
#define IDC_EDIT_CENTERY                1572
#define IDC_BUTTON_F10                  1573
#define IDC_STATIC_END                  1573
#define IDC_EDIT_MIDX                   1574
#define IDC_EDIT_MIDY                   1575
#define IDC_STATIC_SCAN_SPEED           1575
#define IDC_EDIT_ENDX                   1576
#define IDC_EDIT_SPEED                  1576
#define IDC_EDIT_ENDY                   1577
#define IDC_STATIC_CURTIEM              1581
#define IDC_STATIC_DATE1                1582
#define IDC_STATIC_DATE2                1583
#define IDC_STATIC_YEAR1                1585
#define IDC_STATIC_MON1                 1592
#define IDC_STATIC_DAY1                 1593
#define IDC_STATIC_safedistance         1597
#define IDC_RADIO_COAL                  1598
#define IDC_RADIO_CUTOIL                1599
#define IDC_STATIC_OilMode              1600
#define IDC_STATIC_Delay                1601
#define IDC_CHECK_SERIES                1602
#define IDC_STATIC_LeaveDelay           1602
#define IDC_STATIC_LABELWT              1603
#define IDC_STATICORDER                 1604
#define IDC_STATICY1                    1605
#define IDC_STATICZ1                    1606
#define IDC_STATICQ                     1607
#define IDC_STATICR                     1608
#define IDC_STATICYMAX                  1609
#define IDC_STATICZMAX                  1610
#define IDC_STATICQMAX                  1611
#define IDC_GRIDCADCTRL                 1611
#define IDC_STATICRMAX                  1612
#define IDC_BUTTON_SPACE                1612
#define IDC_STATICYREMAIN               1613
#define IDC_BUTTON_GRID                 1613
#define IDC_STATICZREMAIN               1614
#define IDC_BUTTON_FORWORD              1614
#define IDC_STATICQREMAIN               1615
#define IDC_BUTTON_GRID2                1615
#define IDC_STATICRREMAIN               1616
#define IDC_PLANINFOCTRL_SPEED          1616
#define IDC_CHECK_BOTH                  1618
#define IDC_CHECK_THREE                 1619
#define IDC_CHECK_WATER                 1620
#define IDC_BUTTON_VIEW                 1625
#define IDC_BUTTON_TEST                 1626
#define IDC_BUTTON_SCAN                 1627
#define IDC_BUTTON_PRE2                 1633
#define IDC_LAMP_X                      1633
#define IDC_LAMP_READY                  1633
#define IDC_LAMP_LIGHT                  1633
#define IDC_LAMP_Y                      1634
#define IDC_LAMP_Z                      1635
#define IDC_CAPTIONINFO_TITLE           1637
#define IDC_CAPTIONINFO_CONTROL         1638
#define IDC_CAPTIONINFO_RUN             1639
#define IDC_CAPTIONINFO_FILE            1640
#define IDC_PLANINFO_PRESS              1641
#define IDC_CAPTIONINFO_FILENAME        1642
#define IDC_CAPTIONINFO_TITLE2          1643
#define IDC_CAPTIONINFO_TITLE3          1644
#define IDC_LIST_GRID                   1649
#define IDC_CAPTIONINFOCTRL1            1651
#define IDC_BUTTON_PRESSUP              1654
#define IDC_BUTTON_PRESSDOWN            1655
#define IDC_STATIC_RPX                  1656
#define IDC_STATIC_RPY                  1657
#define IDC_STATIC_RPZ                  1658
#define IDC_STATIC_TVX                  1659
#define IDC_STATIC_TVY                  1660
#define IDC_STATIC_TVZ                  1661
#define IDC_STATIC_THICK                1662
#define IDC_EDIT_THICK                  1663
#define IDC_RADIO_SAFEY                 1664
#define IDC_RADIO_SAFEN                 1665
#define IDC_GRID_SHEET                  1665
#define IDC_CAPTION_SHEET               1666
#define IDC_RADIO_SAFE1                 1666
#define IDC_DATETIMEPICKER1             1667
#define IDC_RADIO_SAFE2                 1667
#define IDC_DATETIMEPICKER2             1668
#define IDC_STATIC_START                1669
#define IDC_BUTTON_START                1670
#define IDC_STATIC_WMOVE                1670
#define IDC_RECTEDIT                    1670
#define IDC_STATIC_TPX1                 1671
#define IDC_EDIT_X2MOVE                 1671
#define IDC_STATIC_LIGHT                1671
#define IDC_STATIC_TPX2                 1672
#define IDC_STATIC_HEIGHT               1672
#define IDC_STATIC_X2                   1673
#define IDC_STATIC_COUNT                1673
#define IDC_STATIC_X1                   1674
#define IDC_STATIC_POSTIME              1674
#define IDC_STATIC_UTILITY              1674
#define IDC_EDIT_POSTIME                1675
#define IDC_TRIM_LEFT                   1675
#define IDC_STATIC_LABLE                1676
#define IDC_TRIM_RIGHT                  1676
#define IDC_LIST_GCODE                  1677
#define IDC_TRIM_TOP                    1677
#define IDC_TRIM_BOTTOM                 1678
#define IDC_STATIC_FILEVIEW             1679
#define IDC_STATIC_NO                   1679
#define IDC_EDIT_LABELST                1680
#define IDC_GRIND                       1680
#define IDC_STATIC_STARTPOS             1681
#define IDC_MIN_EDGE                    1681
#define IDC_STATIC_REVERSE              1682
#define IDC_PROJECT                     1682
#define IDC_BUTTON_AGAIN                1683
#define IDC_BUTTON_HAND                 1684
#define IDC_BUTTON_ZOOM                 1685
#define IDC_PARAM_SAVE                  1685
#define IDC_BUTTON_PAN                  1686
#define IDC_STATIC_X                    1687
#define IDC_STATIC_Y                    1688
#define IDC_STATIC_UPTIME               1688
#define IDC_EDIT_UPTIME                 1689
#define IDC_MSCOMM1                     1690
#define IDC_BTN_MIN                     1691
#define IDC_EDIT_TABELY                 1692
#define IDC_BTN_EXCEL                   1695
#define IDC_BUTTON_BTNSTOP              1695
#define IDC_BUTTON_BTNSTART             1696
#define IDC_DISPLAY1                    1821
#define IDC_DISPLAY2                    1822
#define IDC_DISPLAY3                    1823
#define IDC_DISPLAY4                    1824
#define IDC_LIST2                       1901
#define IDC_BUTTON_CS1                  2001
#define IDC_BUTTON_CS2                  2002
#define IDC_BUTTON_CS3                  2003
#define IDC_BUTTON_CS4                  2004
#define IDC_BUTTON_CS5                  2005
#define IDC_BUTTON_CS6                  2006
#define IDC_BUTTON_CS7                  2007
#define IDC_BUTTON_CS8                  2008
#define IDC_BUTTON_CS9                  2009
#define IDC_BUTTON_CS10                 2010
#define IDC_BUTTONF1                    2100
#define IDC_BUTTONF2                    2101
#define IDC_BUTTON_OK                   2114
#define IDC_BUTTON_CANCEL               2115
#define IDC_EDIT_NUM                    2201
#define IDC_STATIC_PARA11               2330
#define IDC_STATIC_PARA12               2331
#define IDC_STATIC_PARA13               2332
#define IDC_STATIC_PARA14               2333
#define IDC_STATIC_PARA15               2334
#define IDC_BUTTON_OILAB                2503
#define IDD_DIALOG_CALCULATOR           14000
#define IDI_ICON_CAL                    14001
#define IDD_DIALOG_SCAN                 14001
#define IDC_EDIT_CODE                   14002
#define IDI_ICON_QUIT                   14002
#define IDD_GRAPH_DIALOG                14002
#define IDC_EDIT_DISTANCE               14003
#define IDD_DIALOG_RECT                 14003
#define IDC_EDIT_CALCODE                14004
#define IDD_DIALOG_RECTOPT              14004
#define IDC_EDIT_CALMOLECULE            14005
#define IDC_EDIT_CALDENOMINATOR         14006
#define IDC_EDIT_PULSE                  14007
#define IDC_STATIC_HIT                  14014
#define IDC_EDIT_MACHINESP              14017
#define IDC_EDIT_SERVOSP                14019
#define IDD_DIALOG_TAB                  14020
#define IDC_A4                          14021
#define IDC_WID                         14022
#define IDC_LEN                         14023
#define IDC_FONT                        14024
#define IDC_MARIN_L                     14025
#define IDC_MARIN_T                     14026
#define IDC_ROWSPACE                    14027
#define IDC_COLSPACE                    14028
#define IDC_ROW                         14029
#define IDC_COL                         14030
#define IDC_MARIN_B                     14031
#define IDC_MARIN_R                     14032
#define IDC_TABCOLSPACE                 14033
#define IDC_BTN_DISPLAY                 14035
#define IDC_EXIT                        14044
#define IDC_TAB_PREVIEW                 14045
#define IDC_REP_PREVIEW                 14046
#define IDC_REP_PNT                     14047
#define IDC_TAB_PNT                     14048
#define IDC_RADIO_TAB                   14049
#define IDC_TAB_PARAM                   14050
#define IDC_STATIC_LEN                  14051
#define IDC_STATIC_WID                  14052
#define IDC_STATIC_FONT                 14053
#define IDC_STATIC_VERSP                14054
#define IDC_STATIC_HORSP                14055
#define IDC_SP_LEFT                     14056
#define IDC_SP_RIGHT                    14058
#define IDC_SP_TOP                      14059
#define IDC_SP_BOTTOM                   14060
#define IDC_STATIC_ROW                  14061
#define IDC_STATIC_COL                  14062
#define IDC_STATIC_TAB_PREVIEW          14063
#define IDC_STATIC_REP_PNT              14064
#define IDC_STATIC_TAB                  14065
#define IDC_STATIC_TABHORSP             14066

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        598
#define _APS_NEXT_COMMAND_VALUE         32771
#define _APS_NEXT_CONTROL_VALUE         1702
#define _APS_NEXT_SYMED_VALUE           104
#endif
#endif
